version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PSW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PSW}
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  sftp:
    image: delfer/alpine-ftp-server
    environment:
      - USERS=${FTP_USER}|${FTP_PSW}
    volumes:
      - ./www:/var/www:delegated
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672